CANCEL_TEXT = '`--CANCELED--`'
ADMIN_PANEL_TEXT = '`--ADMIN--`'
SUCCESS = '`--SUCCESS--`'

# Vk console
VK_CONSOLE_TEXT = '`--VK CONSOLE--`'
# parsing
GET_GROUP_TEXT = '`--GET LINK ON A GROUP--`'
CLOSED_GROUP_TEXT = '`--CLOSED GROUP--`'
GET_COUNT_OF_POSTS_TEXT = '`--GET COUNT OF POSTS--`'
INCORRECT_GROUP_TEXT = '`--INCORRECT GROUP LINK--`'
INCORRECT_COUNT_OF_POSTS = '`--COUNT OF POST MUST BE INTEGER--`'
PARSING_PROCESS = '`--PARSING RUNNING--`'
# link with channel
ADD_GROUP_GET_GROUP_LINK = '`--GET GROUP LINK--`'
ADD_GROUP_LINK_WITH_CHANNEL = '`--LINK THIS GROUP WITH CHANNEL?--`'
CHANNEL_ALREADY_LINKED = '`--THE CHANNEL ALREADY LINKED--`'

LINK_GROUP_WITH_CHANNEL = '`--SELECT CHANNEL--`'
# Tg console
TG_CONSOLE = '`--TG CONSOLE--`'

# Bot config console
BOT_CONFIG_CONSOLE = '`--BOT CONFIG PANEL--`'

START_SCHEDULER = '`START SCHEDULER`'
SHUTDOWN_SCHEDULER = '`SHUTDOWN SCHEDULER`'
REMOVE_ALL_JOBS_SCHEDULER = '`REMOVE ALL JOBS`'

EMPTY_JOB_LIST = '`JOB LIST IS EMPTY`'
