"""Create table

Revision ID: c3e39fae8ed0
Revises: 
Create Date: 2024-01-12 15:31:22.751688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3e39fae8ed0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_channels',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('vk_groups',
    sa.Column('vk_id', sa.BigInteger(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain'),
    sa.UniqueConstraint('vk_id')
    )
    op.create_table('vk_posts',
    sa.Column('vk_post_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vk_post_id')
    )
    op.create_table('tg_channel_vk_group_association',
    sa.Column('tg_channel_id', sa.Integer(), nullable=False),
    sa.Column('vk_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tg_channel_id'], ['tg_channels.id'], ),
    sa.ForeignKeyConstraint(['vk_group_id'], ['vk_groups.id'], ),
    sa.PrimaryKeyConstraint('tg_channel_id', 'vk_group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tg_channel_vk_group_association')
    op.drop_table('vk_posts')
    op.drop_table('vk_groups')
    op.drop_table('users')
    op.drop_table('tg_channels')
    # ### end Alembic commands ###
